services:
  web-service:
    build: .
    container_name: web_thu_vien
    ports:
      - "8000:8080"
    depends_on:
      - db-server
    networks:
      - library-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-server:3306/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_password

  db-server:
    image: mysql:8.0
    container_name: db_thu_vien
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Dòng này giữ lại nếu bạn có sẵn thư mục database chứa file init.sql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-network

volumes:
  db_data:

networks:
  library-network:
    driver: bridge