version: '3.8'

services:
  # 1. Cơ sở dữ liệu MySQL
  db_thu_vien:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_DATABASE: library_db       # Tên Database của bạn (sửa lại cho đúng)
      MYSQL_USER: library_user         # Tài khoản ứng dụng (sửa lại cho đúng)
      MYSQL_PASSWORD: library_pass     # Mật khẩu ứng dụng (sửa lại cho đúng)
      MYSQL_ROOT_PASSWORD: rootpass    # Mật khẩu root bắt buộc phải có
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # 2. Máy chủ Java Spring Boot
  backend_thu_vien:
    build: .  # Build từ file Dockerfile nằm cùng thư mục
    container_name: springboot_backend_server
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_thu_vien:3306/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: library_user
      SPRING_DATASOURCE_PASSWORD: library_pass
    ports:
      - "8000:80" # Ánh xạ cổng 8000 ngoài mặt tiền vào cổng 8080 của Spring Boot
    depends_on:
      - db_thu_vien # Chờ MySQL chạy lên trước rồi mới chạy Backend

volumes:
  db_data: # Giúp lưu dữ liệu MySQL không bị mất khi tắt máy